spring:
  application:
    name: Scope
  config:
    import: optional:file:./config/application.yaml
  datasource:
    url: ${SCOPE_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SCOPE_DB_USER:postgres}
    password: ${SCOPE_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[jdbc.batch_size]": 50
        "[order_inserts]": true
        "[order_updates]": true

jobrunr:
  database:
    table-prefix: t_scp_
  background-job-server:
    enabled: true

logging:
  level:
    root: INFO
  file:
    name: # logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 1GB
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p --- [%t] %-40.40logger{39} : %m%n"
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p --- [%t] %-40.40logger{39} : %m%n"

scope:
  discord:
    token:
  job:
    guild-member-stat:
      cron: "0 * * * *"
    guild-member-event-cleanup:
      cron: "0 0 1 * *"
      retention: 30d
    guild-member-stat-cleanup:
      cron: "0 0 1 * *"
      retention: 30d
    guild-message-event-cleanup:
      cron: "0 0 1 * *"
      retention: 30d

